services:
  qbittorrent-gluetun-PIA-portforward:
    image: qbittorrent-gluetun-pia-portforward:latest
    build: .
    environment:
      - QBITTORRENT_URL=${QBITTORRENT_URL}
      - QBITTORRENT_USERNAME=${QBITTORRENT_USERNAME}
      - QBITTORRENT_PASSWORD=${QBITTORRENT_PASSWORD}
    volumes:
      - ./forwarded_port:/forwarded_port:ro
